// Historical Lucide names remain readable without rewriting existing categories.
const legacy: Record<string, string> = {
  House: "🏠",
  ShoppingBasket: "🛒",
  TrainFront: "🚆",
  Utensils: "🍽️",
  Gamepad2: "🎮",
  HeartPulse: "❤️",
  ShoppingBag: "🛍️",
  Wallet: "💰",
  Ellipsis: "📦",
  Folder: "📁",
};
export const categoryEmoji = (icon?: string) =>
  !icon
    ? "📁"
    : legacy[icon] || (/\p{Extended_Pictographic}/u.test(icon) ? icon : "📁");
export const categoryEmojis = [
  ["📁", "Carpeta"],
  ["📦", "Otros"],
  ["🛒", "Supermercado"],
  ["🍽️", "Restaurante"],
  ["☕", "Café"],
  ["🍕", "Pizza"],
  ["🥑", "Alimentación"],
  ["🍺", "Bebidas"],
  ["🏠", "Casa"],
  ["🏢", "Edificio"],
  ["🔑", "Alquiler"],
  ["💡", "Electricidad"],
  ["💧", "Agua"],
  ["🔥", "Gas"],
  ["📶", "Internet"],
  ["🛋️", "Muebles"],
  ["🧹", "Limpieza"],
  ["🔧", "Reparaciones"],
  ["🚗", "Coche"],
  ["🚌", "Autobús"],
  ["🚆", "Tren"],
  ["🚕", "Taxi"],
  ["🚲", "Bicicleta"],
  ["⛽", "Combustible"],
  ["🅿️", "Parking"],
  ["✈️", "Vuelos"],
  ["🧳", "Viajes"],
  ["🏨", "Hotel"],
  ["🏖️", "Vacaciones"],
  ["❤️", "Salud"],
  ["💊", "Farmacia"],
  ["🩺", "Médico"],
  ["🦷", "Dentista"],
  ["🏋️", "Gimnasio"],
  ["⚽", "Deporte"],
  ["🧘", "Bienestar"],
  ["🛍️", "Compras"],
  ["👕", "Ropa"],
  ["👟", "Calzado"],
  ["💻", "Tecnología"],
  ["📱", "Teléfono"],
  ["🎁", "Regalos"],
  ["💄", "Belleza"],
  ["🎮", "Videojuegos"],
  ["🎬", "Cine"],
  ["🎵", "Música"],
  ["📺", "Televisión"],
  ["📚", "Libros"],
  ["🎨", "Arte"],
  ["🎟️", "Entradas"],
  ["🎉", "Fiestas"],
  ["💰", "Ingresos"],
  ["💼", "Trabajo"],
  ["🏦", "Banco"],
  ["💳", "Tarjeta"],
  ["💸", "Pagos"],
  ["🐷", "Ahorro"],
  ["🧾", "Facturas"],
  ["🎓", "Educación"],
  ["👶", "Bebé"],
  ["🐶", "Mascotas"],
  ["🌱", "Jardín"],
  ["😀", "Sonrisa"],
  ["🥰", "Cariño"],
  ["😎", "Diversión"],
  ["⭐", "Favoritos"],
  ["🌍", "Mundo"],
  ["🤝", "Donaciones"],
];
